# Generated by Django 5.0 on 2024-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
