# Generated by Django 5.1 on 2024-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='submitted', max_length=20),
        ),
    ]
