# Generated by Django 5.0 on 2024-06-10 17:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume_path', verbose_name='Resume'),
        ),
    ]
